innkeep/config/routes.rb
Innkeep::Application.routes.draw do
  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  resources :items do 
    member do
      get :delete
    end
  end

  root :to => "items#index", :constraints => lambda{|req| !req.session[:user_id].blank? }

  root :to => "sessions#new"


end

innkeep/app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :category
  
  def groups
    []
  end

end

innkeep/app/controllers/items_controller.rb
class ItemsController < ApplicationController


  before_filter :login_required

  def index
    @items = Item.paginate(:per_page => 25, :page => params[:page])
    respond_to do |format|
      format.xml{render :text => @items.to_xml}
      format.html{}
    end
  end

  def show
    @item = Item.find_by_code(params[:id])
    respond_to do |format|
      format.html{}
      format.xml{
        if @item
          render :text => @item.to_xml
        else
          render :nothing => true, :status => 404 and return
        end
      }
    end
  end

  def new
    @categories = Category.find(:all)
    @item       = Item.new
  end
  
  def create
    @item = Item.create(params[:item])
    respond_to do |format|
      format.xml{ render :text => @item.to_xml}
      format.html{
        redirect_to item_path(@item) and return
      }
    end
  end
  
  def edit
    @categories = Category.find(:all)    
    @item = Item.find_by_code(params[:id])
  end
  
  def update
    @item = Item.find_by_code(params[:id])    
    if @item.update_attributes(params[:item])    
     respond_to do |format|
       format.html{redirect_to item_path(@item)}
       format.xml{ @item.to_xml }
     end
   else
     respond_to do |format|
       
     end
   end        
  end
  
  def delete
    @item = Item.find_by_code(params[:id])
    if @item.destroy
      redirect_to :back and return
    else
      redirect_to :back and return      
    end
  end
  
end

innkeep/app/helpers/items_helper.rb
module ItemsHelper
end

innkeep/app/views/items/_form.html.erb
<div class="field"><label for="fname">Name </label>
	<%= text_field :item, :name, {:size => 50, :class => "medium"}%>
	<p class="field_help">
		EC-Radio Chip
	</p>
	</div>

<div class="field"><label for="description">Description</label> 
	<%= text_area :item, :description, {:rows => 7, :cols => 50}%>
	<p class="field_help">
		EC-Radio Chip, mounted on Arduino Duo								
	</p>
</div>

<div class="field"><label for="fname">Code </label>
	<%= text_field :item, :code, {:size => 50, :class => "medium"}%>
	<p class="field_help">
		1223-4331-3322<br />
		<span style="color:red">
			Make sure this code is a valid barcode, otherwise - you'll get weird results.<br /> Click 
			<a href="#">here</a> to generate a barcode on the fly!
		</span>
	</p>
	</div>


<div class="field">
	<label for="type">Type </label>
	<select id="type" class="medium" name="item[category_id]">
		<optgroup label="Category">
			<%= options_from_collection_for_select(@categories, 'id', 'name', @item.category_id )%>
		</optgroup>
	</select>
	<p class="field_help">Electronics, tactictal</p>
</div>

innkeep/app/views/items/edit.html.erb
<div id="masthead">
	
	<div class="content_pad">
		
		<h1 class="">Edit <%= @item.name %></h1>
		
		<div id="bread_crumbs">
			<a href="../dashboard.html">Home</a> / 
			<a href="<%= items_path %>">Items</a> / 
			<a href="javascript:;" class="current_page">Edit</a>				
		 </div> <!-- #bread_crumbs -->
		
		<div id="search">
			<form action="/search" method="get">
				<input type="text" value="" placeholder="Search" name="search" id="search_input" title="Search" />					
				<input type="submit" value="" name="submit" class="submit" />					
			</form>
		</div> <!-- #search -->
		
	</div> <!-- .content_pad -->
	
</div> <!-- #masthead -->	

<div id="content" class="xgrid">
	
	<div class="x12">
		
		<%= form_tag(item_path(@item.code), {:class => "form label-inline uniform", :method => :put}) do %>
		<%= render :partial => "form" %>
						
						<br />
						<div class="buttonrow">
							<button class="btn">Save</button> or <a href="<%= items_path %>">cancel</a>
						</div>

						<% end %>
		
	</div> <!-- .x12 -->
	
</div> <!-- #content -->

<% content_for :page_script do %>
	$(".uniform").uniform();
<% end %>

innkeep/app/views/items/index.html.erb
<div id="masthead">

	<div class="content_pad">

		<h1 class="">Items</h1>

		<div id="bread_crumbs">
			<a href="/">Home</a> / 
			<a href="javascript:;" class="current_page">Items</a>				
		</div> <!-- #bread_crumbs -->

		<div id="search">
			<form action="/search" method="get">
				<input type="text" value="" placeholder="Search" name="search" id="search_input" title="Search" />					
				<input type="submit" value="" name="submit" class="submit" />					
			</form>
		</div> <!-- #search -->

	</div> <!-- .content_pad -->

</div> <!-- #masthead -->	

<div id="content" class="xgrid">

	<div class="x12">


		<h2>All Items</h2>	

		<a href="<%= new_item_path %>">New item</a>

		<table class="data display">
			<thead>
				<tr>
					<th>Name</th>
					<th>Category</th>
					<th>Groups</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<% @items.each do |item| %>
				<tr class="<%= cycle('even', 'odd') %>">
					<td><%= link_to item.name, item_path(item.code) %></td>
					<td>Cname</td>
					<td><%= item.groups.collect{|a| a.name}.join(",")%></td>
					<td class="center">
						<%= link_to 'Edit', edit_item_path(item.code) %>
						| 
						<%= link_to 'Delete', delete_item_path(item.code) %>
					</td>
					</tr>
					<% end %>
					<% if @items.empty? %>
					<tr>
						<td class="center">
							No items saved yet
						</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>	
					<% end %>
				</tbody>
			</table>

			<br /><br /><br />

		</div> <!-- .x12 -->

	</div> <!-- #content -->

innkeep/app/views/items/new.html.erb
<div id="masthead">
	
	<div class="content_pad">
		
		<h1 class="">Add Item</h1>
		
		<div id="bread_crumbs">
			<a href="../dashboard.html">Home</a> / 
			<a href="<%= items_path %>">Items</a> / 
			<a href="javascript:;" class="current_page">New</a>				
		 </div> <!-- #bread_crumbs -->
		
		<div id="search">
			<form action="/search" method="get">
				<input type="text" value="" placeholder="Search" name="search" id="search_input" title="Search" />					
				<input type="submit" value="" name="submit" class="submit" />					
			</form>
		</div> <!-- #search -->
		
	</div> <!-- .content_pad -->
	
</div> <!-- #masthead -->	

<div id="content" class="xgrid">
	
	<div class="x12">
		
		<%= form_tag(items_path, {:class => "form label-inline uniform"}) do %>
		<%= render :partial => "form" %>
						
						<br />
						<div class="buttonrow">
							<button class="btn">Save</button> or <a href="<%= items_path %>">cancel</a>
						</div>

						<% end %>
		
	</div> <!-- .x12 -->
	
</div> <!-- #content -->

<% content_for :page_script do %>
	$(".uniform").uniform();
<% end %>

innkeep/app/views/items/show.html.erb
<div id="masthead">
	
	<div class="content_pad">
		
		<h1 class=""><%= @item.name %></h1>
		
		<div id="bread_crumbs">
			<a href="../dashboard.html">Home</a> / 
			<a href="<%= items_path %>">Items</a> / 
			<a href="javascript:;" class="current_page"><%= @item.name %></a>				
		 </div> <!-- #bread_crumbs -->
		
		<div id="search">
			<form action="/search" method="get">
				<input type="text" value="" placeholder="Search" name="search" id="search_input" title="Search" />					
				<input type="submit" value="" name="submit" class="submit" />					
			</form>
		</div> <!-- #search -->
		
	</div> <!-- .content_pad -->
	
</div> <!-- #masthead -->	

<div id="content" class="xgrid">
	
	<div class="x12">
		<h1><%= @item.name %></h1>
		Nothing here yet.
	</div> <!-- .x12 -->
	
</div> <!-- #content -->

<% content_for :page_script do %>
	$(".uniform").uniform();
<% end %>